version: "3.9"
services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      - action_server

  action_server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
